sudo: required

services:
  - docker

before_install:
  - docker build -t test .

script:
  # describe: should render latex
  # * biblatex biber
  # * math
  # * utf8 chars
  - docker run --rm -v $PWD:/data test /bin/bash -c "cd test && pdflatex test && biber test && pdflatex test && pdflatex test"
  
